image:
  repository: registry.pipeline.dev.vriyas.com/private/image-compress
  tag: latest
  pullPolicy: IfNotPresent
ingress:
  enabled: true
  host: image-compress.pipeline.dev.vriyas.com
resources:
  limits:
    cpu: 100m
    memory: 256Mi
  requests:
    cpu: 80m
    memory: 128Mi
imagePullSecrets:
  name: regcred
readinessProbe:
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1
