image:
  repository: registry.idcix.net/idcix/aubrieta
  tag: latest
  pullPolicy: IfNotPresent
ingress:
  enabled: true
  host: aubrieta.idcix.net
resources:
  limits:
    cpu: 100m
    memory: 256Mi
  requests:
    cpu: 80m
    memory: 128Mi
imagePullSecrets:
 - name: regcred
readinessProbe:
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1
